# https://docs.docker.com/build/ci/github-actions/multi-platform/
name: Build and push Docker DEV image

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'charts/**'
      - 'docker-*.sh'
      - '*.md'
    branches: [master]
  workflow_dispatch:
env:
  REGISTRY_IMAGE: arawak123/kanbam

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: arawak123
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=dev

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
